version: '2'

services:

  node1:
    image: docker:1.12.0-rc2-dind
    privileged: true
    ports:
      - "2377:2377"
    volumes:
      - node1:/var/lib/docker

  node2:
    image: docker:1.12.0-rc2-dind
    privileged: true
    volumes:
      - node2:/var/lib/docker
    depends_on:
      - node1

  node3:
    image: docker:1.12.0-rc2-dind
    privileged: true
    volumes:
      - node3:/var/lib/docker
    depends_on:
      - node1


volumes:
  node1: {}
  node2: {}
  node3: {}
